### ISSUE TITLE
Deprecate parTraverse in favor of parMap

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2788]
- [ ] Rename parTraverse to parMap
- [ ] Remove parTraverse signatures that don't preserve the correct CoroutineDispatcher context
- [ ] Remove parTraverseEither
- [ ] Remove parTraverseResult
- [ ] Rename parTraverseValidated to parMapAccumulating, and use Either#mapAccumulating instead.

**Comment by serras** [comment]
Fixed by #2795

**Comment by nomisRev** [comment]
This didn't happen in #2795, and needs to still happen. A couple fixes have to be made to `parTraverse` in order to preserve context in a similar was as KotlinX Coroutine does.

This can however happen in 1.x.x straight away, so I am removing _Arrow 2.0_ from the issue name.

**Comment by thejeff77** [comment]
The documentation does not mention deprecation or the new method FYI. 

https://old.arrow-kt.io/docs/apidocs/arrow-fx-coroutines/arrow.fx.coroutines/par-traverse-n.html
